[DEVOPS-740] Add support for Blue/Green Deployments (#230)
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-740"
title="DEVOPS-740" target="_blank">DEVOPS-740</a></summary>
  <br />
  <table>
    <tr>
      <th>Summary</th>
      <td>Research: A/B deployments</td>
    </tr>
    <tr>
      <th>Type</th>
      <td>
<img alt="Research"
src="https://amuniversal.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10501?size=medium"
/>
        Research
      </td>
    </tr>
    <tr>
      <th>Status</th>
      <td>In Progress</td>
    </tr>
    <tr>
      <th>Points</th>
      <td>N/A</td>
    </tr>
    <tr>
      <th>Labels</th>
      <td>-</td>
    </tr>
  </table>
</details>
<!--
do not remove this marker as it will break action-jira-linter's
functionality.
  added_by_jira_lint
-->
---

<!-- Please make sure you read the contribution guidelines and then fill
out the blanks below.

Please format the PR title appropriately based on the type of change:
  [JIRA-XXX]: <description>
-->

## Description

Add support for Blue/Green Deployments
- Automatically determines the active/inactive environment based off the
last deployment's AKS Ingress hostname.
- If the `BLUE_GREEN_DEPLOYMENT` repository variable is set to `true`,
and the environment is production, and the last deployment was in the
"blue" environment, then add "-green" after the environment in the
ingress hostname and vice versa. (NOTE: Only works if the
`environmentIngress` input is set to `true`, otherwise it doesn't have a
place to add the "-green").
- Automatically update the Bunny CDN origin linked to the app if blue
green deployments are enabled.

<img width="2078" height="834" alt="bluegreendeployments"
src="https://github.com/user-attachments/assets/ec9a4a55-fb0c-499c-82e2-ab6021497b81"
/>
<img width="895" height="270" alt="bunnyCdnUpdates"
src="https://github.com/user-attachments/assets/47e4b346-9202-472e-bf18-d955775947e9"
/>




## Related Links

<!-- List any links related to this pull request here

Replace "JIRA-XXX" with the your Jira issue key -->

- Jira Issue: DEVOPS-740
- Testing environment: [![🚀
Deploy](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/workflows/deploy.yml/badge.svg?branch=research%2FDEVOPS-740%2Fa-b-deployments&event=push)](https://github.com/Andrews-McMeel-Universal/reusable_workflows-test/actions/runs/21260684795)

diff --git a/.github/workflows/aks-deploy.yaml b/.github/workflows/aks-deploy.yaml
--- a/.github/workflows/aks-deploy.yaml
+++ b/.github/workflows/aks-deploy.yaml
@@ -95,6 +95,21 @@ on:
         required: false
         type: string
         default: ${{ vars.ENV_ENCRYPTION_SECRET }}
+      blueGreenDeployment:
+        required: false
+        type: string
+        description: "Enable blue/green deployment strategy"
+        default: ${{ vars.BLUE_GREEN_DEPLOYMENT || 'false' }}
+      bunnyCdnDomain:
+        required: false
+        type: string
+        description: "Bunny CDN Domain. Set to the domain of your Bunny CDN."
+        default: ${{ vars.BUNNY_CDN_DOMAIN }}
+      updateBunnyCdnOrigin:
+        required: false
+        type: string
+        description: "Enable updating Bunny CDN pull zone origin after deployment"
+        default: ${{ vars.UPDATE_BUNNY_CDN_ORIGIN || 'false' }}
     secrets:
       azureClusterName:
         required: true
@@ -116,6 +131,8 @@ on:
         required: false
       sentryAuthToken:
         required: false
+      bunnyCdnApiKey:
+        required: false
 
 jobs:
   build:
@@ -133,6 +150,50 @@ jobs:
         shell: pwsh
         run: |
           Install-Module -Name powershell-yaml -Force
+
+      - name: Install PowerShell modules for Accessing Azure Table Storage
+        if: inputs.blueGreenDeployment == 'true' && inputs.environment == 'production'
+        shell: pwsh
+        run: |
+          Install-Module -Name AzTable,Az.Storage,Az.Resources -Force
+
+      - name: Get Blue/Green Deployment Info
+        id: bg-deployment
+        if: inputs.blueGreenDeployment == 'true' && inputs.environment == 'production'
+        shell: pwsh
+        env:
+          storageAccountName: amucloudapps
+          appInfoTableName: DeployedApplications
+          repositoryName: ${{ github.event.repository.name }}
+          environment: ${{ inputs.environment }}
+        run: |
+          # Get Blue/Green Deployment Info
+          $storageAccountKey = ${{ secrets.storageAccountKey }}
+          $storageContext = New-AzStorageContext -StorageAccountName ${env:storageAccountName} -StorageAccountKey $storageAccountKey
+
+          #Get Storage table
+          try {
+              $appInfoTable = (Get-AzStorageTable -Name ${env:appInfoTableName} -Context $storageContext -ErrorAction Stop).CloudTable
+              }
+          catch {
+              Write-Error -Message "Error accessing cloud ${env:appInfoTableName} table.  Error message was: $_.Exception.Message"
+              return
+          }
+
+          $aksIngress = (Get-AzTableRow -Table $appInfoTable -partitionKey ${env:repositoryName} -RowKey ${env:environment} -SelectColumn "AksIngress").AksIngress
+
+          if ($aksIngress -match "-green") {
+              $activeDeployment = "green"
+              $inactiveDeployment = "blue"
+          }
+          else {
+              $activeDeployment = "blue"
+              $inactiveDeployment = "green"
+          }
+          Write-Output "activeDeployment=$activeDeployment"
+          Write-Output "activeDeployment=$activeDeployment" >> $env:GITHUB_ENV
+          Write-Output "blueGreenInactiveDeployment=$inactiveDeployment"
+          Write-Output "blueGreenInactiveDeployment=$inactiveDeployment" >> $env:GITHUB_ENV
 
       - name: Login via Az module
         if: inputs.haIngress == 'true'
@@ -162,6 +223,8 @@ jobs:
           haIngress: ${{ inputs.haIngress }}
           chartsPath: ./deployments/charts
           datacenterLocation: ${{ env.datacenterLocation }}
+          blueGreenDeployment: ${{ inputs.blueGreenDeployment }}
+          blueGreenInactiveDeployment: ${{ env.blueGreenInactiveDeployment }}
         run: |
           # Extract Helm values
 
@@ -226,7 +289,12 @@ jobs:
 
           # Add environment to ingress
           if ($environmentIngress -ne "false") {
-              $ingress = "${env:appEnvironment}.$ingress"
+              if ($env:blueGreenDeployment -eq "true" -and $env:appEnvironment -eq "production") {
+                  $ingress = "${env:appEnvironment}-${env:blueGreenInactiveDeployment}.$ingress"
+              }
+              else {
+                  $ingress = "${env:appEnvironment}.$ingress"
+              }
           }
 
           # Add datacenter location to ingress if HA hostname is enabled
@@ -357,6 +425,7 @@ jobs:
       minReplicas: ${{ env.minReplicas }}
       chartsPath: ${{ env.chartsPath }}
       wwwIngress: ${{ env.wwwIngress }}
+      blueGreenInactiveDeployment: ${{ env.blueGreenInactiveDeployment }}
       datacenterLocation: ${{ env.datacenterLocation }}
 
   deploy:
@@ -391,6 +460,8 @@ jobs:
           wwwIngress: ${{ needs.build.outputs.wwwIngress }}
           ingress: ${{ needs.build.outputs.ingress }}
           ingressWhitelist: ${{ inputs.ingressWhitelist }}
+          blueGreenDeployment: ${{ inputs.blueGreenDeployment }}
+          blueGreenInactiveDeployment: ${{ needs.build.outputs.blueGreenInactiveDeployment }}
         run: |
           # Create values override file
 
@@ -485,20 +556,37 @@ jobs:
 
               # Add environment to ingress
               if ($environmentIngress -ne "false") {
-                  $item.host = "${env:environment}.$($item.host)"
-                  Write-Output "Adding environment to $($item.name): $($item.host)"
+                  if ($env:blueGreenDeployment -eq "true" -and $env:environment -eq "production") {
+                      $item.host = "${env:environment}-${env:blueGreenInactiveDeployment}.$($item.host)"
+                      Write-Output "Adding environment and inactive deployment to $($item.name): $($item.host)"
+                  }
+                  else {
+                      $item.host = "${env:environment}.$($item.host)"
+                      Write-Output "Adding environment to $($item.name): $($item.host)"
+                  }
               }
 
               # Add ingressClassName to ingress
-              $item.ingressClassName = "nginx-${env:environment}"
+              if ($env:blueGreenDeployment -eq "true" -and $env:environment -eq "production") {
+                  # Set ingress class name
+                  $item.ingressClassName = "nginx-${env:environment}-${env:blueGreenInactiveDeployment}"
+
+                  # Add cluster issuer annotation
+                  $item.annotations."cert-manager.io/cluster-issuer" = "letsencrypt-${env:environment}-${env:blueGreenInactiveDeployment}"
+              }
+              else {
+                  # Set ingress class name
+                  $item.ingressClassName = "nginx-${env:environment}"
+
+                  # Add cluster issuer annotation
+                  $item.annotations."cert-manager.io/cluster-issuer" = "letsencrypt-${env:environment}"
+              }
 
               # Reset annotations
               if ($null -eq $item.annotations) {
                   $item.annotations = @{}
               }
 
-              # Add cluster issuer annotation
-              $item.annotations."cert-manager.io/cluster-issuer" = $clusterIssuer
 
               # Add whitelist annotation
               $item.annotations."nginx.ingress.kubernetes.io/limit-whitelist" = "$env:adminIngressWhitelist"
@@ -677,10 +765,14 @@ jobs:
         env:
           ENVIRONMENT_NAMESPACE: ${{ inputs.environmentNamespace }}
           ENVIRONMENT: ${{ inputs.environment }}
+          BLUE_GREEN_DEPLOYMENT: ${{ inputs.blueGreenDeployment }}
+          BLUE_GREEN_INACTIVE_DEPLOYMENT: ${{ needs.build.outputs.blueGreenInactiveDeployment }}
         run: |
           # Switch Kubernetes Namespace
-
-          if [ "${ENVIRONMENT_NAMESPACE}" == "true" ]; then
+          if [ $ENVIRONMENT_NAMESPACE == "true" ]; then
+            if [ $BLUE_GREEN_DEPLOYMENT == "true" ] && [ $ENVIRONMENT == "production" ]; then
+              ENVIRONMENT="${ENVIRONMENT}-${BLUE_GREEN_INACTIVE_DEPLOYMENT}"
+            fi
             kubectl config set-context --current --namespace="${ENVIRONMENT}"
             echo "namespace=${ENVIRONMENT}" >> $GITHUB_OUTPUT
           else
@@ -815,6 +907,8 @@ jobs:
         env:
           ENVIRONMENT: ${{ inputs.environment }}
           ENVIRONMENT_NAMESPACE: ${{ inputs.environmentNamespace }}
+          BLUE_GREEN_DEPLOYMENT: ${{ inputs.blueGreenDeployment }}
+          BLUE_GREEN_INACTIVE_DEPLOYMENT: ${{ needs.build.outputs.blueGreenInactiveDeployment }}
           INGRESS_DOMAIN_NAME: ${{ needs.build.outputs.domainName }}
           INGRESS_DOMAINS: ${{ steps.values-override.outputs.domains }}
           DATACENTER_LOCATION: ${{ needs.build.outputs.datacenterLocation }}
@@ -828,7 +922,13 @@ jobs:
           else
             INGRESS="${AKS_CLUSTER_NAME}"
           fi
-          AKS_INGRESS="${INGRESS}-ingress.${DATACENTER_LOCATION}.cloudapp.azure.com."
+
+          # Set AKS ingress FQDN
+          if [ "${BLUE_GREEN_DEPLOYMENT}" == "true" ] && [ "${ENVIRONMENT}" == "production" ]; then
+            AKS_INGRESS="${INGRESS}-${BLUE_GREEN_INACTIVE_DEPLOYMENT}-ingress.${DATACENTER_LOCATION}.cloudapp.azure.com."
+          else
+            AKS_INGRESS="${INGRESS}-ingress.${DATACENTER_LOCATION}.cloudapp.azure.com."
+          fi
           echo "aksIngress=${AKS_INGRESS}"
           echo "aksIngress=${AKS_INGRESS}" >> "$GITHUB_OUTPUT"
 
@@ -851,6 +951,49 @@ jobs:
               --cname "${AKS_INGRESS}" \
               --ttl 3600
           done
+
+      - name: Update Bunny CDN origin URL
+        if: inputs.bunnyCdnDomain != '' && inputs.blueGreenDeployment == 'true' && inputs.environment == 'production'
+        shell: pwsh
+        env:
+          bunnyCdnDomain: ${{ inputs.bunnyCdnDomain }}
+          environment: ${{ inputs.environment }}
+          dnsPrimaryDomain: ${{ steps.values-override.outputs.dnsPrimaryDomain }}
+          ingressDomainName: ${{ needs.build.outputs.domainName }}
+        run: |
+          # Update Bunny CDN origin URL
+          $bunnyCdnApiKey = "${{ secrets.bunnyCdnApiKey }}"
+          $originUrl = "https://${env:dnsPrimaryDomain}.${env:ingressDomainName}"
+
+          # Set headers
+          $headers = @{
+              "AccessKey" = "$bunnyCdnApiKey"
+              "accept" = "application/json"
+              "content-type" = "application/json"
+          }
+          $body = @{
+              "PreloadingScreenShowOnFirstVisit" = "true"
+              "OriginUrl" = "$originUrl"
+          } | ConvertTo-Json
+
+          # Get Pull Zone ID
+          $uri = "https://api.bunny.net/pullzone?page=0&perPage=1000&search=${env:bunnyCdnDomain}&includeCertificate=false"
+          $bunnyCdnPullZoneId = (Invoke-WebRequest -Headers $headers -Uri $uri -Method 'GET' | ConvertFrom-Json).Items.Id
+
+          # Update origin URL
+          Write-Output "Updating Bunny CDN origin URL to: ${originUrl}"
+          $uri = "https://api.bunny.net/pullzone/${bunnyCdnPullZoneId}"
+          $response = (Invoke-WebRequest -Headers $headers -Uri $uri -Method 'POST' -Body $body | ConvertFrom-Json)
+
+          # Verify update
+          if ($response.OriginUrl -match "$originUrl") {
+              Write-Output "Bunny CDN origin URL was updated successfully"
+          }
+          else {
+              throw "Bunny CDN origin URL update response did not contain the expected origin URL."
+              Write-Output "Output: $response"
+              exit 1
+          }
 
       - name: Create Sentry release
         if: env.NEXT_PUBLIC_SENTRY_DSN && inputs.publishSentryRelease == 'true'
