[HOTFIX] Replace htpasswd command with openssl equivalent

diff --git a/.github/workflows/aks-deploy.yaml b/.github/workflows/aks-deploy.yaml
--- a/.github/workflows/aks-deploy.yaml
+++ b/.github/workflows/aks-deploy.yaml
@@ -769,27 +769,25 @@ jobs:
           kubectl create secret generic "${APP_NAME}-config-secret" --validate='warn' --from-env-file ${{ github.workspace }}/.env
 
       - name: Update basic web authentication Kubernetes secret
+        if: ${{ inputs.webAuthentication == 'true' }}
         shell: bash
         env:
-          WEB_AUTHENTICATION: ${{ inputs.webAuthentication }}
           APP_NAME: ${{ needs.build.outputs.appName }}
         run: |
           # Update basic web authentication Kubernetes secret
           WEB_AUTHENTICATION_USERNAME="${{ secrets.webAuthenticationUsername }}"
           WEB_AUTHENTICATION_PASSWORD="${{ secrets.webAuthenticationPassword }}"
 
-          if [[ "${WEB_AUTHENTICATION}" == "true" ]]; then
-              if [[ -z "${WEB_AUTHENTICATION_USERNAME}" ]] || [[ -z "${WEB_AUTHENTICATION_PASSWORD}" ]]; then
-                  echo "::error::Please make sure the 'webAuthenticationUsername' and 'webAuthenticationPassword' GitHub environment secrets are set correctly."
-                  exit 1
-              fi
-          
-              if kubectl get secret "${APP_NAME}-basic-auth" > /dev/null 2>&1; then
-                  kubectl delete secret "${APP_NAME}-basic-auth"
-              fi
-              htpasswd -cb auth "${WEB_AUTHENTICATION_USERNAME}" "${WEB_AUTHENTICATION_PASSWORD}"
-              kubectl create secret generic "${APP_NAME}-basic-auth" --from-file=auth
+          if [[ -z "${WEB_AUTHENTICATION_USERNAME}" ]] || [[ -z "${WEB_AUTHENTICATION_PASSWORD}" ]]; then
+              echo "::error::Please make sure the 'webAuthenticationUsername' and 'webAuthenticationPassword' GitHub environment secrets are set correctly."
+              exit 1
           fi
+          
+          if kubectl get secret "${APP_NAME}-basic-auth" > /dev/null 2>&1; then
+              kubectl delete secret "${APP_NAME}-basic-auth"
+          fi
+          printf "${WEB_AUTHENTICATION_USERNAME}:$(openssl passwd -5 ${WEB_AUTHENTICATION_PASSWORD})\n" > auth
+          kubectl create secret generic "${APP_NAME}-basic-auth" --from-file=auth
 
       - name: Create K8s Image Pull Secret
         uses: azure/k8s-create-secret@v5
