added some error handling

diff --git a/.github/workflows/aks-deploy.yaml b/.github/workflows/aks-deploy.yaml
--- a/.github/workflows/aks-deploy.yaml
+++ b/.github/workflows/aks-deploy.yaml
@@ -203,6 +203,8 @@ jobs:
           if [[ -n "$PREVIOUS_MANIFEST" ]]; then
             echo "Unlocking previous manifest: ${PREVIOUS_MANIFEST}"
             az acr repository update --name "${{ secrets.registryHostName }}" --image "${{ github.event.repository.name }}@${PREVIOUS_MANIFEST}" --delete-enabled true --write-enabled true
+          else
+            echo "Previous manifest could not be found. Skipping unlocking."
           fi
 
       - name: Build Docker Image
@@ -387,6 +389,10 @@ jobs:
         id: get-current-image
         run: |
           CURRENT_IMAGE=$(kubectl get deployment "${{ needs.build.outputs.appName }}" -n "${{ steps.namespace.outputs.namespace }}" -o=jsonpath='{$.spec.template.spec.containers[:1].image}' | awk -F '/' '{print $2}')
+          if [ -z "${CURRENT_IMAGE}" ]; then
+            echo "Failed to get current image"
+            exit 1
+          fi
           echo "currentImage=${CURRENT_IMAGE}" >> $GITHUB_OUTPUT
 
       - name: Deploy to Azure Kubernetes Service
@@ -412,6 +418,10 @@ jobs:
       - name: Disable write access for newly deployed image
         run: |
           IMAGE_MANIFEST=$(az acr repository show --name "${{ secrets.registryHostName }}" --image "${{ github.event.repository.name }}:${{ github.sha }}" --query "digest" -o tsv)
+          if [ -z "${IMAGE_MANIFEST}" ]; then
+            echo "Failed to get current image manifest"
+            exit 1
+          fi
           az acr repository update --name "${{ secrets.registryHostName }}" --image "${{ github.event.repository.name }}@${IMAGE_MANIFEST}" --delete-enabled false --write-enabled false
 
       - name: Create or Update Public DNS Record
