DEVOPS-add-web-auth-error-message (#19)
* add web auth error msg

* moved new web auth validation to web auth check

* fix pwsh if statement

* trying to fix web auth / ingress whitelist checks

* fix web auth vars in github secrets step

* fix quote issue + simplified web auth checks

* more specific web auth error msg

diff --git a/.github/workflows/aks-deploy.yaml b/.github/workflows/aks-deploy.yaml
--- a/.github/workflows/aks-deploy.yaml
+++ b/.github/workflows/aks-deploy.yaml
@@ -288,6 +288,11 @@ jobs:
           kubectl create secret generic "${{ env.configSecret }}" --from-env-file .env
 
           if ( "${{ inputs.webAuthentication }}" -eq "true") {
+            if (!"${{ secrets.webAuthenticationUsername }}" -or !"${{ secrets.webAuthenticationPassword }}") {
+                echo "::error::Please make sure the 'webAuthenticationUsername' and 'webAuthenticationPassword' GitHub environment secrets are set correctly."
+                exit 1
+            }
+
             if (kubectl get secret | Select-String "${{ env.appName }}-basic-auth") {
               kubectl delete secret "${{ env.appName }}-basic-auth"
             }
@@ -313,16 +318,16 @@ jobs:
           WEB_AUTHENTICATION=$(echo "${{ inputs.webAuthentication }}" | tr -d "'" | tr -d '"')
           INGRESS_WHITELIST_ENV="${{ env.ingressWhitelist }}"
           ADMIN_INGRESS_WHITELIST_ENV="${{ env.adminIngressWhitelist }}"
-          if [[ -n "${INGRESS_WHITELIST_ENV}" ]] ; then
-            INGRESS_WHITELIST="${{ env.ingressWhitelist }}"
-          else
+          if [[ -z "${INGRESS_WHITELIST_ENV}" ]] ; then
             INGRESS_WHITELIST="${{ inputs.ingressWhitelist }}"
+          else
+            INGRESS_WHITELIST="${{ env.ingressWhitelist }}"
           fi
 
-          if [[ -n "${ADMIN_INGRESS_WHITELIST_ENV}" ]] ; then
-            ADMIN_INGRESS_WHITELIST="${{ env.adminIngressWhitelist }}"
-          else
+          if [[ -z "${ADMIN_INGRESS_WHITELIST_ENV}" ]] ; then
             ADMIN_INGRESS_WHITELIST="${{ inputs.adminIngressWhitelist }}"
+          else
+            ADMIN_INGRESS_WHITELIST="${{ env.adminIngressWhitelist }}"
           fi
 
           if [[ "${WEB_AUTHENTICATION}" == "true" ]] ; then
@@ -338,7 +343,7 @@ jobs:
             annotations:
               nginx.ingress.kubernetes.io/whitelist-source-range: "${ADMIN_INGRESS_WHITELIST}"
           EOF
-          elif [[ "${ADMIN_INGRESS_WHITELIST}" != "207.67.20.252" ]] || [[ "${INGRESS_WHITELIST}" != "0.0.0.0/0" ]]; then
+          else
           cat << EOF >> values-override.yaml
           ingress:
             annotations:
@@ -347,13 +352,6 @@ jobs:
           adminingress:
             annotations:
               nginx.ingress.kubernetes.io/whitelist-source-range: "${ADMIN_INGRESS_WHITELIST}"
-          EOF
-          else
-          cat << EOF >> values-override.yaml
-          ingress:
-            annotations:
-              nginx.ingress.kubernetes.io/limit-whitelist: "207.67.20.252"
-              nginx.ingress.kubernetes.io/whitelist-source-range: "${INGRESS_WHITELIST}"
           EOF
           fi
 
