[HOTFIX] Add debugging for env var creation in Azure Function App Deploy workflow

diff --git a/.github/workflows/azfunction-deploy.yaml b/.github/workflows/azfunction-deploy.yaml
--- a/.github/workflows/azfunction-deploy.yaml
+++ b/.github/workflows/azfunction-deploy.yaml
@@ -302,18 +302,41 @@ jobs:
 
             echo "Adding $key to app settings"
             if [[ "${{ inputs.environment }}" == "production" ]]; then
-              az functionapp config appsettings set \
-                -g "${{ inputs.AZURE_FUNCTIONAPP_RESOURCEGROUP }}" \
-                -n "${{ inputs.AZURE_FUNCTIONAPP_NAME }}" \
-                --slot-settings "$key=@Microsoft.KeyVault(VaultName=${{ env.keyVaultName }};SecretName=${VARIABLE_LC})" >/dev/null && \
-              echo "Successfully added $key to app settings"
+              if [[ '${{ runner.debug }}' == '1' ]]; then
+                az functionapp config appsettings set \
+                  -g "${{ inputs.AZURE_FUNCTIONAPP_RESOURCEGROUP }}" \
+                  -n "${{ inputs.AZURE_FUNCTIONAPP_NAME }}" \
+                  --slot-settings "$key=@Microsoft.KeyVault(VaultName=${{ env.keyVaultName }};SecretName=${VARIABLE_LC})"
+              else
+                az functionapp config appsettings set \
+                  -g "${{ inputs.AZURE_FUNCTIONAPP_RESOURCEGROUP }}" \
+                  -n "${{ inputs.AZURE_FUNCTIONAPP_NAME }}" \
+                  --slot-settings "$key=@Microsoft.KeyVault(VaultName=${{ env.keyVaultName }};SecretName=${VARIABLE_LC})" >/dev/null
+              fi
+              if [[ $? -ne 0 ]]; then
+                echo "::error::Failed to add $key to app settings"
+              else
+                echo "Successfully added $key to app settings"
+              fi
             else
-              az functionapp config appsettings set \
-                -g "${{ inputs.AZURE_FUNCTIONAPP_RESOURCEGROUP }}" \
-                -n "${{ inputs.AZURE_FUNCTIONAPP_NAME }}" \
-                --slot "${{ inputs.environment }}" \
-                --slot-settings "$key=@Microsoft.KeyVault(VaultName=${{ env.keyVaultName }};SecretName=${VARIABLE_LC})" >/dev/null && \
-              echo "Successfully added $key to app settings"
+              if [[ '${{ runner.debug }}' == '1' ]]; then
+                az functionapp config appsettings set \
+                  -g "${{ inputs.AZURE_FUNCTIONAPP_RESOURCEGROUP }}" \
+                  -n "${{ inputs.AZURE_FUNCTIONAPP_NAME }}" \
+                  --slot "${{ inputs.environment }}" \
+                  --slot-settings "$key=@Microsoft.KeyVault(VaultName=${{ env.keyVaultName }};SecretName=${VARIABLE_LC})"
+              else
+                az functionapp config appsettings set \
+                  -g "${{ inputs.AZURE_FUNCTIONAPP_RESOURCEGROUP }}" \
+                  -n "${{ inputs.AZURE_FUNCTIONAPP_NAME }}" \
+                  --slot "${{ inputs.environment }}" \
+                  --slot-settings "$key=@Microsoft.KeyVault(VaultName=${{ env.keyVaultName }};SecretName=${VARIABLE_LC})" >/dev/null && \
+              fi
+              if [[ $? -ne 0 ]]; then
+                echo "::error::Failed to add $key to app settings"
+              else
+                echo "Successfully added $key to app settings"
+              fi
             fi
           done
 
