[DEVOPS-796] Fix bug with leading slash in scope with az role assignment command

diff --git a/.github/workflows/azwebapp-deploy.yaml b/.github/workflows/azwebapp-deploy.yaml
--- a/.github/workflows/azwebapp-deploy.yaml
+++ b/.github/workflows/azwebapp-deploy.yaml
@@ -171,16 +171,24 @@ jobs:
           AZURE_KEYVAULT_NAME: ${{ env.keyVaultName }}
           AZURE_IDENTITY: ${{ env.appIdentity }}
         run: |
-          set -eu
           # Retrieve the Key Vault ID
-          keyVaultId=$(az keyvault show --name "${AZURE_KEYVAULT_NAME}" --query id --output tsv)
-          
-          # Assign the Key Vault Secrets User role to the managed identity using object ID and principal type
-          az role assignment create --role "Key Vault Secrets User" --assignee-object-id "${AZURE_IDENTITY}" --assignee-principal-type ServicePrincipal --scope "${keyVaultId}"
+          keyVaultId="$(az keyvault show --name "${AZURE_KEYVAULT_NAME}" --query id --output tsv)"
 
-          if [[ $? -ne 0 ]]; then
+          # Try role assignment with the Key Vault ID as-is
+          if ! az role assignment create \
+            --role "Key Vault Secrets User" \
+            --assignee-object-id "${AZURE_IDENTITY}" \
+            --assignee-principal-type ServicePrincipal \
+            --scope "${keyVaultId}"
+          then
+            # If it fails, retry after stripping a leading slash
             keyVaultId="${keyVaultId#/}"
-            az role assignment create --role "Key Vault Secrets User" --assignee-object-id "${AZURE_IDENTITY}" --assignee-principal-type ServicePrincipal --scope "${keyVaultId}"
+
+            az role assignment create \
+              --role "Key Vault Secrets User" \
+              --assignee-object-id "${AZURE_IDENTITY}" \
+              --assignee-principal-type ServicePrincipal \
+              --scope "${keyVaultId}"
           fi
       
       - name: Retrieve environment variables
