Retrieve PR info based off issue PR number

diff --git a/.github/workflows/ephemeral-deploy.yaml b/.github/workflows/ephemeral-deploy.yaml
--- a/.github/workflows/ephemeral-deploy.yaml
+++ b/.github/workflows/ephemeral-deploy.yaml
@@ -3,10 +3,6 @@ name: Ephemeral Deployment
 on:
   workflow_call:
     inputs:
-      environment:
-        required: true
-        type: string
-        description: "Deploy Environment.  This is used to pull in and set the github environment. Can be development, staging, or production."
       environmentKeyVaultPrefix:
         required: false
         type: string
@@ -56,25 +52,30 @@ on:
       JIRA_TOKEN:
         required: true
 
-env:
-  githubPrBranch: ${{ github.head_ref }}
-  githubPrTitle: ${{ github.event.pull_request.title }}
-  githubPrDescription: ${{ github.event.pull_request.body }}
-
 jobs:
   prepare:
     name: Preparation Step
     if: ${{ github.event_name != 'pull_request' && github.event.action != 'closed' }}
     runs-on: ubuntu-latest
     steps:
-      - name: Retrieve Jira ticket ID
-        id: jira-ticket
-        run: |
-          PR_BRANCH=$(echo "${{ env.githubPrBranch }}" | grep -Eo "\b[A-Z][A-Z0-9_]+-[1-9][0-9]*" || true)
-          PR_TITLE=$(echo "${{ env.githubPrTitle }}" | grep -Eo "\b[A-Z][A-Z0-9_]+-[1-9][0-9]*" || true)
-          PR_DESC=$(echo "${{ env.githubPrDescription }}" | grep -Eo "\b[A-Z][A-Z0-9_]+-[1-9][0-9]*" || true)
+      - name: Install jq
+        uses: dcarbone/install-jq-action@v2.1.0
 
-          for var in ${PR_BRANCH} ${PR_TITLE} ${PR_DESC}; do JIRA_TICKET_ID=$(echo $var | grep -E ".") && break ; done
+      - name: Get Jira ticket ID from pull request information
+        if: ${{ github.event.issue.pull_request }}
+        run: |
+          # Use GitHub's REST API to get pull request information
+          PR_NUMBER=${{ github.event.issue.number }}
+          PR_DETAILS=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+               -H "Accept: application/vnd.github.v3+json" \
+               "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER")
+
+          # Extract the PR branch (head ref), title, and description (body)
+          PR_BRANCH=$(echo "${PR_DETAILS}" | jq -r '.head.ref' | grep -Eo "\b[A-Z][A-Z0-9_]+-[1-9][0-9]*" || true)
+          PR_TITLE=$(echo "${PR_DETAILS}} | jq -r '.title' | grep -Eo "\b[A-Z][A-Z0-9_]+-[1-9][0-9]*" || true)
+          PR_DESCRIPTION=$(echo "${PR_DETAILS}" | jq -r '.body' | grep -Eo "\b[A-Z][A-Z0-9_]+-[1-9][0-9]*" || true)
+
+          for var in ${PR_BRANCH} ${PR_TITLE} ${PR_DESCRIPTION}; do JIRA_TICKET_ID=$(echo $var | grep -E ".") && break ; done
           if [ -z "${JIRA_TICKET_ID}" ]; then
             echo "::error A Jira issue key is missing from your branch name, pull request title, and pull request description. Please confirm it is linked properly in the pull request."
             exit 1
@@ -90,7 +91,26 @@ jobs:
           REPOSITORY_NAME="${{ inputs.repositoryName }}"
           REPO_NAME_SHORT=$(echo "${REPOSITORY_NAME:0:21}" | tr '[:upper:]' '[:lower:]' | tr "_" "-")
           echo "repositoryName=${REPO_NAME_SHORT}" >> $GITHUB_OUTPUT
+
+      - name: Get Environment
+        id: environment
+        shell: bash
+        run: |
+          COMMENT_BODY="${{ github.event.comment.body }}"
+          if [[ "${COMMENT_BODY}" =~ "/deploy" ]] ; then
+            ENVIRONMENT="${COMMENT_BODY#/deploy }"
+            if [ -n "${ENVIRONMENT}" ]; then
+              echo "environment=${ENVIRONMENT}" >> $GITHUB_OUTPUT
+            else
+              echo "::error::Unable to extract environment from comment. Please post a comment with '/deploy [ENVIRONMENT]'"
+              exit 1
+            fi
+          else
+            echo "::error::Deployment environment not found. Please post a comment with '/deploy [ENVIRONMENT]'"
+            exit 1
+          fi
     outputs:
+      environment: ${{ steps.environment.outputs.environment }}
       jiraTicketId: ${{ steps.jira-ticket.outputs.jiraTicketId }}
       jiraTicketIdLc: ${{ steps.jira-ticket.outputs.jiraTicketIdLc }}
       repositoryName: ${{ steps.repository-name.outputs.repositoryName }}
@@ -110,9 +130,9 @@ jobs:
         id: get-envs
         uses: Andrews-McMeel-Universal/get-envs@v1
         with:
-          environment: ${{ inputs.environment }}
+          environment: ${{ needs.prepare.outputs.environment }}
           azurecredentials: ${{ secrets.azureCredentials }}
-          environmentKeyVault: ${{ inputs.environmentKeyVaultPrefix }}-${{ inputs.environment }}
+          environmentKeyVault: ${{ inputs.environmentKeyVaultPrefix }}-${{ needs.prepare.outputs.environment }}
           contentTypes: BuildArg Env
 
       - name: Get target port
@@ -196,9 +216,9 @@ jobs:
         id: get-envs
         uses: Andrews-McMeel-Universal/get-envs@v1
         with:
-          environment: ${{ inputs.environment }}
+          environment: ${{  needs.prepare.outputs.environment }}
           azurecredentials: ${{ secrets.azureCredentials }}
-          environmentKeyVault: ${{ inputs.environmentKeyVaultPrefix }}-${{ inputs.environment }}
+          environmentKeyVault: ${{ inputs.environmentKeyVaultPrefix }}-${{ needs.prepare.outputs.environment }}
           contentTypes: BuildArg Env
 
       - name: Update Next URL variables
@@ -322,7 +342,7 @@ jobs:
           comment: |
             This ticket has been linked to an ephemeral deployment.
             - URL: ${{ needs.deploy.outputs.hostname }}
-            - Environment APIs: ${{ inputs.environment }}
+            - Environment APIs: ${{ needs.prepare.outputs.environment }}
 
   destroy:
     name: Destroy Azure Container Instance
@@ -333,9 +353,9 @@ jobs:
       - name: Generate .env file from Azure Key Vaults
         uses: Andrews-McMeel-Universal/get-envs@v1
         with:
-          environment: ${{ inputs.environment }}
+          environment: ${{ needs.prepare.outputs.environment }}
           azurecredentials: ${{ secrets.azureCredentials }}
-          environmentKeyVault: ${{ inputs.environmentKeyVaultPrefix }}-${{ inputs.environment }}
+          environmentKeyVault: ${{ inputs.environmentKeyVaultPrefix }}-${{ needs.prepare.outputs.environment }}
 
       - name: Delete Azure Resources
         run: |
