[DEVOPS-304] Determine ephemeral deployment environment key vault to use based off PR description (#82)
<details open>
<summary><a href="https://amuniversal.atlassian.net/browse/DEVOPS-304"
title="DEVOPS-304" target="_blank">DEVOPS-304</a></summary>
  <br />
  <table>
    <tr>
      <th>Summary</th>
<td>Use checkboxes in the PR description to determine the ephemeral
deployment's APIs</td>
    </tr>
    <tr>
      <th>Type</th>
      <td>
<img alt="Story"
src="https://amuniversal.atlassian.net/images/icons/issuetypes/story.png"
/>
        Story
      </td>
    </tr>
    <tr>
      <th>Status</th>
      <td>In Progress</td>
    </tr>
    <tr>
      <th>Points</th>
      <td>N/A</td>
    </tr>
    <tr>
      <th>Labels</th>
      <td>-</td>
    </tr>
  </table>
</details>
<!--
do not remove this marker as it will break action-jira-linter's
functionality.
  added_by_jira_lint
-->
---

<!-- Please make sure you read the contribution guidelines and then fill
out the blanks below.

Please format the PR title appropriately based on the type of change:
  [JIRA-XXX]: <description>
-->

## Description

- Determine which environment key vault to use based off of what
environment is checked off in the PR description.
  - Removed `environment` input
- Replaced `environmentKeyVault` input with `environmentKeyVaultPrefix`
input that defaults to the repository's `${{ vars.AZURE_KEYVAULT_PREFIX
}}` variable

## Related Links

<!-- List any links related to this pull request here

Replace "JIRA-XXX" with the your Jira issue key -->

- Jira Issue: DEVOPS-304
- Working test:
- [![📦️ Deploy Ephemeral
Environment](https://github.com/Andrews-McMeel-Universal/puzzle-society_ui/actions/workflows/ephemeral-deployments.yml/badge.svg?branch=story%2FDEVOPS-304%2Fdetermine-environment-based-off-pr-description-checkboxes)](https://github.com/Andrews-McMeel-Universal/puzzle-society_ui/actions/workflows/ephemeral-deployments.yml)
- Testing environment pull request description:
![image](https://github.com/Andrews-McMeel-Universal/reusable_workflows/assets/111298136/5a090acb-203f-4375-a724-768122380895)

diff --git a/.github/workflows/ephemeral-deploy.yaml b/.github/workflows/ephemeral-deploy.yaml
--- a/.github/workflows/ephemeral-deploy.yaml
+++ b/.github/workflows/ephemeral-deploy.yaml
@@ -3,14 +3,11 @@ name: Ephemeral Deployment
 on:
   workflow_call:
     inputs:
-      environment:
-        required: true
-        type: string
-        description: "Deploy Environment.  This is used to pull in and set the github environment. Can be development, staging, or production."
-      environmentKeyVault:
+      environmentKeyVaultPrefix:
         required: false
         type: string
-        description: "AKS Key vault."
+        description: "AKS Key vault prefix."
+        default: ${{ vars.AZURE_KEYVAULT_PREFIX }}
       repositoryName:
         required: false
         type: string
@@ -74,6 +71,10 @@ jobs:
           PR_DESC=$(echo "${{ env.githubPrDescription }}" | grep -Eo "\b[A-Z][A-Z0-9_]+-[1-9][0-9]*" || true)
 
           for var in ${PR_BRANCH} ${PR_TITLE} ${PR_DESC}; do JIRA_TICKET_ID=$(echo $var | grep -E ".") && break ; done
+          if [ -z "${JIRA_TICKET_ID}" ]; then
+            echo "::error A Jira issue key is missing from your branch name, pull request title, and pull request description. Please confirm it is linked properly in the pull request."
+            exit 1
+          fi
           JIRA_TICKET_ID_LC=$(echo "${JIRA_TICKET_ID}" | tr '[:upper:]' '[:lower:]')
 
           echo "jiraTicketIdLc=${JIRA_TICKET_ID_LC}" >> $GITHUB_OUTPUT
@@ -85,7 +86,21 @@ jobs:
           REPOSITORY_NAME="${{ inputs.repositoryName }}"
           REPO_NAME_SHORT=$(echo "${REPOSITORY_NAME:0:21}" | tr '[:upper:]' '[:lower:]' | tr "_" "-")
           echo "repositoryName=${REPO_NAME_SHORT}" >> $GITHUB_OUTPUT
+
+      - name: Get Environment
+        id: environment
+        shell: bash
+        run: |
+          DESCRIPTION="${{ env.githubPrDescription }}"
+          ENVIRONMENT=$(echo "${DESCRIPTION}" | grep -Eo "\- \[x\] .+ Key Vaults"  | awk -F ' ' '{print $3}' | tr '[:upper:]' '[:lower:]')
+          if [ -n "${ENVIRONMENT}" ]; then
+            echo "environment=${ENVIRONMENT}" >> $GITHUB_OUTPUT
+          else
+            echo "::notice::Unknown environment key vault. Defaulting to development key vault."
+            echo "environment=development" >> $GITHUB_OUTPUT
+          fi
     outputs:
+      environment: ${{ steps.environment.outputs.environment }}
       jiraTicketId: ${{ steps.jira-ticket.outputs.jiraTicketId }}
       jiraTicketIdLc: ${{ steps.jira-ticket.outputs.jiraTicketIdLc }}
       repositoryName: ${{ steps.repository-name.outputs.repositoryName }}
@@ -105,9 +120,9 @@ jobs:
       - name: Generate .env file from Azure Key Vaults
         uses: Andrews-McMeel-Universal/get-envs@v1
         with:
-          environment: ${{ inputs.environment }}
+          environment: ${{ needs.prepare.outputs.environment }}
           azurecredentials: ${{ secrets.azureCredentials }}
-          environmentKeyVault: ${{ inputs.environmentKeyVault }}
+          environmentKeyVault: ${{ inputs.environmentKeyVaultPrefix }}-${{ needs.prepare.outputs.environment }}
 
       - name: Set environment variables
         id: env-vars
@@ -122,9 +137,9 @@ jobs:
       - name: Generate build args from Azure Key Vaults
         id: build-args
         run: |
-          ENVIRONMENT="${{ inputs.environment }}"
+          ENVIRONMENT="${{ needs.prepare.outputs.environment }}"
           REPOSITORY_NAME="${{ inputs.repositoryName }}"
-          ENV_KEYVAULT_NAME="${{ inputs.environmentKeyVault }}"
+          ENV_KEYVAULT_NAME="${{ inputs.environmentKeyVaultPrefix }}-${{ needs.prepare.outputs.environment }}"
 
           # Check if searching for key vaults by repository name or otherwise, if key vault name argument is given
           if [ -z "${ENV_KEYVAULT_NAME}" ]; then
@@ -223,9 +238,9 @@ jobs:
       - name: Generate .env file from Azure Key Vaults
         uses: Andrews-McMeel-Universal/get-envs@v1
         with:
-          environment: ${{ inputs.environment }}
+          environment: ${{ needs.prepare.outputs.environment }}
           azurecredentials: ${{ secrets.azureCredentials }}
-          environmentKeyVault: ${{ inputs.environmentKeyVault }}
+          environmentKeyVault: ${{ inputs.environmentKeyVaultPrefix }}-${{ needs.prepare.outputs.environment }}
 
       - name: Add B2C Redirect URI
         run: |
@@ -332,9 +347,9 @@ jobs:
       - name: Generate .env file from Azure Key Vaults
         uses: Andrews-McMeel-Universal/get-envs@v1
         with:
-          environment: ${{ inputs.environment }}
+          environment: ${{ needs.prepare.outputs.environment }}
           azurecredentials: ${{ secrets.azureCredentials }}
-          environmentKeyVault: ${{ inputs.environmentKeyVault }}
+          environmentKeyVault: ${{ inputs.environmentKeyVaultPrefix }}-${{ needs.prepare.outputs.environment }}
 
       - name: Delete Azure Resources
         run: |
