[DEVOPS-620] Optimize reusable workflows

diff --git a/.github/workflows/purge-cdn.yaml b/.github/workflows/purge-cdn.yaml
--- a/.github/workflows/purge-cdn.yaml
+++ b/.github/workflows/purge-cdn.yaml
@@ -28,16 +28,6 @@ jobs:
     name: Purge CDN Cache
     runs-on: ubuntu-latest
     steps:
-      - name: Check inputs
-        uses: azure/powershell@v2
-        with:
-          azPSVersion: "latest"
-          inlineScript: |
-            if ((!"${{ inputs.environment }}") -and ((!"${{ inputs.cdnResourceGroup }}") -or (!"${{ inputs.cdnProfile }}") -or (!"${{ inputs.cdnEndpoint }}"))) {
-              echo "::error::The environment input and at least one of the CDN inputs are missing from the workflow call. Please try again"
-              exit 1
-            }
-
       - name: Login via Az module
         uses: azure/login@v2
         with:
@@ -45,27 +35,25 @@ jobs:
           enable-AzPSSession: true
 
       - name: Purge CDN cache
-        uses: azure/powershell@v2
-        with:
-          azPSVersion: "latest"
-          inlineScript: |
-            if (-not ${{ inputs.cdnResourceGroup }}) {
-              Write-Error "CDN Resource Group is required. Please provide the CDN Resource Group name when calling the workflow."
-              exit 1
-            }
+        shell: pwsh
+        run: |
+          if (-not ${{ inputs.cdnResourceGroup }}) {
+            Write-Error "CDN Resource Group is required. Please provide the CDN Resource Group name when calling the workflow."
+            exit 1
+          }
 
-            if (-not ${{ inputs.cdnProfile }}) {
-              Write-Error "CDN Profile is required. Please provide the CDN Profile name when calling the workflow."
-              exit 1
-            }
+          if (-not ${{ inputs.cdnProfile }}) {
+            Write-Error "CDN Profile is required. Please provide the CDN Profile name when calling the workflow."
+            exit 1
+          }
 
-            if (-not ${{ inputs.cdnEndpoint }}) {
-              Write-Error "CDN Endpoint is required. Please provide the CDN Endpoint name when calling the workflow."
-              exit 1
-            }
+          if (-not ${{ inputs.cdnEndpoint }}) {
+            Write-Error "CDN Endpoint is required. Please provide the CDN Endpoint name when calling the workflow."
+            exit 1
+          }
 
-            $ResourceGroup = "${{ inputs.cdnResourceGroup }}"
-            $ProfileName = "${{ inputs.cdnProfile }}"
-            $EndpointName = "${{ inputs.cdnEndpoint }}"
+          $ResourceGroup = "${{ inputs.cdnResourceGroup }}"
+          $ProfileName = "${{ inputs.cdnProfile }}"
+          $EndpointName = "${{ inputs.cdnEndpoint }}"
 
-            Clear-AzCdnEndpointContent -EndpointName $EndpointName -ProfileName $ProfileName -ResourceGroupName $ResourceGroup -ContentPath '/*'
+          Clear-AzCdnEndpointContent -EndpointName $EndpointName -ProfileName $ProfileName -ResourceGroupName $ResourceGroup -ContentPath '/*'
